import './individuales/user.spec';
import './individuales/usercard.spec';
import './individuales/trade.spec';
import './individuales/card.spec';
import './individuales/notification.spec';
import './individuales/preferences.spec';
import './individuales/pokemon.spec';
import './individuales/sync.spec';
import './individuales/advanced-features.spec';
import './individuales/advanced-usercards.spec';
import './individuales/advanced-trades.spec';
import './individuales/socket_helpers.spec';
import './individuales/jwt_helpers.spec';
import './individuales/validation_helpers.spec';
import './individuales/friend_helpers_extended.spec';
import './individuales/pack_helpers_extended.spec';
import './individuales/trade_helpers_extended.spec';
import './individuales/response_helpers_extended.spec';
import './individuales/user_helpers_extended.spec';
import './individuales/mongo_helpers_extended.spec';
import './individuales/cardDataBuilder.spec';
import './individuales/cardDataBuilder-advanced.spec';
import './individuales/cards-advanced.spec';
import './individuales/tcgdx-advanced.spec';
import './individuales/createTestUser-advanced.spec';
import './individuales/cardDataBuilder_services_extended.spec';
import './individuales/cards_services_extended.spec';
import './client/users.slice.spec';
import './client/cards.slice.spec';
import './client/trades.slice.spec';
import './client/notifications.slice.spec';
import './client/preferences.slice.spec';
import './client/collection.slice.spec';
import './client/whistlist.slice.spec';
import './client/features/usersSlice.spec';
import './client/features/cardsSlice.spec';
import './client/features/tradesSlice.spec';
import './client/features/notificationsSlice.spec';
import './client/features/preferencesSlice.spec';
import './client/features/collectionSlice.spec';
import './client/features/whislistSlice.spec';
import './client/authService.spec';
import './client/socket.spec';
// import './client/apiService.spec'; // File not found
import './client/hooks.spec';
import './client/utils.spec';
import './client/redux-slices.spec';
import './client/apiService-comprehensive.spec';
import './client/apiService-extended.spec';
import './client/useLanguage.spec';
import './client/i18n.spec';
import './client/store.spec';
import './client/pages.spec';
import './server/middleware.spec';
import './server/models.spec';
import './server/index.spec';
import './server/scripts.spec';
import './server/services.spec';
import './server/trade-router.spec';
import './server/trade-router-extended.spec';
import './server/trade-router-comprehensive.spec';
import './server/trade-router-extended2.spec';
import './server/friend-trade-router.spec';
import './server/friend-trade-router-extended.spec';
import './server/trade-request-router.spec';
import './server/trade-request-router-extended.spec';
import './server/trade_request-router-complete.spec';
// import './server/trade-router-full-coverage.spec'; // Endpoints no implementados
// import './server/trade-request-full-coverage.spec'; // Endpoints no implementados
import './server/users-router.spec';
import './server/users-router-extended.spec';
import './server/users-router-additional.spec';
import './server/users-router-comprehensive.spec';
import './server/users-router-coverage.spec';
import './server/users-router-integration-coverage.spec';
import './server/usercard-router-extended.spec';
import './server/usercard-router-complete.spec';
// import './server/usercard-router-full-coverage.spec'; // Endpoints no implementados
import './server/users-extended.spec';
import './server/card-router-extended.spec';
import './server/card-router-comprehensive.spec';
import './server/preferences-router-complete.spec';
// Deshabilitados - endpoints no completamente implementados (retornan 501)
// import './server/trade-missing-coverage.spec';
// import './server/trade-request-missing-coverage.spec';
// import './server/usercard-missing-coverage.spec';
// import './server/userHelpers.spec'; // File not found
import './server/tradeHelpers-extended.spec';
import './server/userHelpers-extended.spec';
import './integration/utilities.spec';
import './integration/validation.spec';